import { join } from "node:path";
import { readFileSync, writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { loadConfig, loadRules, pathAllowed, isGenerated, matchAny, readJsonl, sha256, fail } from "./lib.mjs";

/**
 * Confronts a handoff's declared files with the real git diff.
 *
 * Reports both directions: a file modified but undeclared, and a file
 * declared but never touched. Applies the role's file policy to the observed
 * paths, not to the declared ones.
 *
 * A generated path is refused outright for every role but the orchestrator.
 * The project map is a function of the whole source tree: an issue that
 * commits it commits a state including whatever a parallel agent had
 * half-written, and the reviewer then reads a diff its author cannot
 * account for. One writer regenerates it once the issue is closed.
 *
 * Usage: node verify-scope.mjs <handoff.json> <base-ref>
 */
function main() {
  const args = process.argv.slice(2).filter((arg) => arg !== "--json");
  const recordAt = args.indexOf("--record");
  const recordTo = recordAt === -1 ? null : args[recordAt + 1];
  const [handoffPath, baseRef] = recordAt === -1 ? args : args.filter((_, index) => index !== recordAt && index !== recordAt + 1);
  if (!handoffPath || !baseRef) fail("usage : verify-scope.mjs <handoff.json> <base-ref>");
  const handoff = JSON.parse(readFileSync(handoffPath, "utf8"));
  const rules = loadRules();
  const config = loadConfig();
  const sha = handoff.evidence?.commit_sha;
  if (!sha) fail("the handoff carries no commit_sha, nothing to verify");

  let diff;
  try {
    diff = execFileSync("git", ["diff", "--name-only", "-z", "--no-renames", `${baseRef}..${sha}`, "--"], { encoding: "utf8" });
  } catch (error) {
    fail(`git diff a echoue : ${error.message}`);
  }
  const changed = diff.split("\0").filter((line) => line.length > 0);
  const declared = new Set(handoff.evidence.files ?? []);
  const policy = rules.file_policy?.[handoff.agent];
  const errors = [];
  const issueId = handoff.scope?.issue_id;
  const entry = handoff.agent === "orchestrator" ? null : readJsonl(join(config.store_dir, "issues.jsonl")).find((item) => item.record.id === issueId);
  const reservations = entry?.record.pipeline_state?.file_reservations ?? [];
  if (handoff.agent !== "orchestrator" && entry == null) errors.push("Issue record missing: scope.issue_id must name the reservation owner");
  const reserved = (file) => reservations.some((pattern) => matchAny(file, [pattern]) ||
    (!/[*?]/.test(pattern) && file.startsWith(pattern.replace(/\/$/, "") + "/")));

  const generated = (file) => isGenerated(file, config);
  const writesGenerated = handoff.agent === "orchestrator";

  for (const file of changed) {
    if (generated(file)) {
      if (!writesGenerated) {
        errors.push(
          `generated file committed by ${handoff.agent}: ${file}. It is regenerated by the orchestrator ` +
            "once the issue closes, from a tree where no other agent is mid-write.",
        );
      }
      continue;
    }
    if (handoff.agent !== "orchestrator" && !reserved(file)) errors.push(`outside issue reservations: ${file}`);
    if (!declared.has(file)) errors.push(`modified but undeclared: ${file}`);
    if (!pathAllowed(file, policy)) errors.push(`hors role ${handoff.agent} : ${file}`);
  }
  for (const file of declared) {
    if (generated(file)) continue;
    if (!changed.includes(file)) errors.push(`declared but never touched: ${file}`);
  }

  if (errors.length > 0) {
    for (const error of errors) console.error(`scope : ${error}`);
    process.exit(1);
  }
  if (process.argv.includes("--json")) {
    console.log(JSON.stringify({ issue_id: issueId ?? null, agent: handoff.agent, base_ref: baseRef, commit_sha: sha,
      record_hash: entry ? sha256(entry.raw) : null, files: changed, reservations, checked_at: new Date().toISOString(), status: "passed" }));
    return;
  }
  const verdict = `scope verified: ${changed.length} file(s), ${baseRef}..${sha}, role ${handoff.agent}, ${new Date().toISOString()}`;
  // Records the verdict where QA's task package will look for it. Without
  // this the field arrived empty three times running in a host project, while
  // the QA prompt promised the timestamped output was there: QA re-ran the
  // command by hand, or believed it. A proof the package announces and cannot
  // carry is worse than an absent one, because it reads as done.
  if (recordTo != null) {
    writeFileSync(recordTo, JSON.stringify({ issue_id: issueId ?? null, agent: handoff.agent, base_ref: baseRef,
      commit_sha: sha, files: changed, reservations, checked_at: new Date().toISOString(), status: "passed",
      said: verdict }, null, 2) + "\n");
  }
  console.log(verdict);
}

main();
